### PR TITLE
Call AAXtoMP3 interactively

### PR DESCRIPTION
**Pull request by Nicko98**
This script interactively asks the user for the options to call AAXtoMP3 with.
I only implemented codec, compression, chapters, authcode, loglevel and source file because I wanted the dialog to be short.
If wanted the other options can be added. Preferably in a way that they only appeare if `--advanced` is used.

### CODE REVIEW

**Comment by Nicko98** [comment]
Any concerns or something I should change?

**Comment by KrumpetPirate** [comment]
I'm not sure how useful having this wrapper script would be personally. Using it a few times I got frustrated having to re-enter information on a new computer due to missing dependencies or the output not being what I wanted (trying to be a good tester, screwed it up a couple of times). I'd see that as being how the script's usage would go for a new user too.

I'm not going to do it but it seems that a GUI driven application would be easier for the non-technical user more than this interactive wrapper.

Thoughts?

**Comment by Nicko98** [comment]
Ok regarding the issue with re-entering information, this could be fixed with a save-file which stores the way AAXtoMP3 was called last time so that one could recall this and only change the aax-file which btw. can be chosen by drag-n-drop of the file when I make it ignore the single quotes that get added around the path when dropping a file in the terminal (at least on ubuntu).

I'm not really into GUI-coding as well. Would be happy if someone replaced this by a GUI and would work on improving that, if the first running version is done.
But this is what I can offer right now and with the little changes I mentioned in the upper paragraph of this comment it should be relatively comfortable for non-technical users...

**Comment by Nicko98** [comment]
Now I've added the changes I mentioned in my last comment:

The script writes a .savefile which stores the chosen options.
The next time the script restores from this .savefile, so if you want the same options you only have to confirm them.
When asked for a file, one can drag'n'drop it in the terminal (at least in ubuntu)
-> In Ubuntu drag'n'drop results in the string '/path/to/file' so I just remove the single quotes before and after the path
-> I don't how other distros, Windows and Mac handle this, but if they either just put the path or put the path surrounded by single quotes like Ubuntu, drag'n'drop works there too.

This isn't a GUI, I know, but up until someone writes a GUI, I think this is near enough.

**Comment by KrumpetPirate** [comment]
I can confirm the single quote file drop works on Manjaro as well (GNOME too though, hopefully KDE or whatever doesn't mess with that).

I'm going to merge then add a .gitignore entry for the .interactivesave file and chmod it on the main branch.

Thanks for the contribution.

**Pull request merged**
