### PR TITLE
feat: Use ffmpeg to cover add instead of mp4art

### PR DESCRIPTION
**Pull request by nysasounds**
Use ffmpeg to cover add instead of mp4art from deprecated mp4v2-utils package

closes: https://github.com/KrumpetPirate/AAXtoMP3/issues/198

### CODE REVIEW

**Comment by KrumpetPirate** [comment]
Thanks for your contribution

**Comment by fabh2o** [comment]
I think that this doesnt work for all codec: ffmpeg errors when it tries to add the cover file to m4b file
```
[ipod @ 0x55846d1bf600] Could not find tag for codec mjpeg in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 --
```
`./AAXtoMP3/AAXtoMP3 -e:m4b --loglevel 3 *.aaxc`

Seems like it's causing https://github.com/KrumpetPirate/AAXtoMP3/issues/203#issuecomment-1033045048

**Comment by nysasounds** [comment]
> I think that this doesnt work for all codec: ffmpeg errors when it tries to add the cover file to m4b file
> 
> ```
> [ipod @ 0x55846d1bf600] Could not find tag for codec mjpeg in stream #1, codec not currently supported in container
> Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
> Error initializing output stream 0:1 --
> ```
> 
> `./AAXtoMP3/AAXtoMP3 -e:m4b --loglevel 3 *.aaxc`
> 
> Seems like it's causing [#203 (comment)](https://github.com/KrumpetPirate/AAXtoMP3/issues/203#issuecomment-1033045048)

Let me take a quick look.

**Comment by nysasounds** [comment]
This reverts the regression, and still enables cover art on newer Debian/Ubuntu releases for non mpeg-4 containers.

https://github.com/KrumpetPirate/AAXtoMP3/pull/205

**Pull request merged**
