### PR TITLE
Large Pull request

### PR DESCRIPTION
**Pull request by upuv**
### Comment ###
I decided that I should probably push this up to the top.  

I've made a number of changes.  Mostly it's about cleanup.  I have merged the latest functionality added by you and other in your repo.

I changed the indentation to 2 spaces vs 4.  Just to fit on my screen and I'm old and that's how we did it in the 80's and 90's

### Changes ###
* options are now un-ordered and include a short and long version.
* added a --targetdir option
* added a --debug option
* DEBUG now dumps some fairly verbose output.
* Code Commenting
* Readme.md updates.  Lots of rewrites.  More to be done.
* added -h option
* added option validation
* Some formating of naming strings changed.  Minor.
* Added debug_file function.  Dumps a named file to STDOUT
* merged --opus --aac --flac options.
* BREAKING I have change the default behaviour of authcode. Authcode is now an optional option.
* m3u Playlist support

### Issues ###
* flac encoding is restricted in this code to be a single file. Multi file output breaks in my testing.
* Extra file AAXtoM4B is present.  Intended to be deprecated in up coming version.

### Feature requests ###
* I plan to remove the m4b version.  But in order to do that I will actually create a suite of container options.  Example:  Making video file with static image and the audio stream.

### CODE REVIEW

**Comment by KrumpetPirate** [comment]
I will have to test these changes when I get some extra time. I would also like for a test to be run on OSX, but I have no way of doing that at this time.

**Comment by KrumpetPirate** [comment]
Sucks that the file batching got removed, but it makes sense to get flag support in. Why not use getopts type input?

**Comment by upuv** [comment]
The getopts support across various OS and versions of of bash doesn't necessarily support short and long variants of options. I'm lazy I wanted the short version of options. :) 

As I'm a linux nerd and not an apple person I wasn't able or sure about how getopts shell edededed or external options would work. I found what I felt to be a nice and easily understandable bit of code that I have no doubt will work on all bash implementations.  I hold no promises with the recent windows excursion into linux compatibility. I currently don't have a device with the latest windows builds.

The breaking change.  Is in my code I no longer allow for AUTHCODE as a pseudo optional parm.  It's now an option/switch. Of course the .authcode files are default.  This makes it a breaking change and should justify a v2 release.

**Comment by KrumpetPirate** [comment]
Okay I will test it when I get the opportunity. Thanks!

**Comment by upuv** [comment]
After a ton more testing and numerous bug fixes the master is now clean.

Thanks to @jostyee for all the testing and recommendations.

That turned out to be more changes than I originally thought.  As near as I can tell this is feature complete and properly tested.

**Comment by KrumpetPirate** [comment]
Your commits seem to be good, I need to do some testing on my side. Do you think this is in a state ready for review?

**Comment by upuv** [comment]
My testing shows it's solid.  A few others gave given it a thumbs up.

I'll branch my local to work on personalised directory and output naming.  Thus it won't get in the way of your testing.

I just today added validation code of aax files.  I had issues with broken downloads from my audible library. Thus the feature.

The code however has moved on a fair bit from your original.  So it might take you some time to validate.

**Comment by KrumpetPirate** [comment]
I've accidentally created a merge conflict with your branch. I will attempt to resolve this when I get some free time.

**Comment by dmitrij-drandarov** [comment]
@upuv "flac encoding is restricted in this code to be a single file. Multi file output breaks in my testing."

Fixed in PR #72  :)

**Comment by upuv** [comment]
@dmitrij-drandarov have you tested this with the other outputs?

From the documentation it appears to be valid.  In the next few days I will try the option out in my env. 

I'll be glad to remove this restriction.

**Comment by dmitrij-drandarov** [comment]
@upuv Since the code change is in the "chapter-extraction-code" I only tested the non-single-file outputs. Seemed to work without any problems. 
Tested OPUS/AAC/FLAC/DEFAULT MP3.

I also made some other changes to the "chapter-extraction-code" in #75

**Comment by dmitrij-drandarov** [comment]
PR now fixes: #70  #76 #65

**Comment by KrumpetPirate** [comment]
Thanks for your work on this, I really appreciate it.

**Comment by KrumpetPirate** [comment]
Had to revert this PR. You have merge conflict artifacts that break the code. Checked your master fork and it's there too..

**Pull request merged**
